#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

working_dir="$(dirname ${0})"

source "${working_dir}/_sourced/constants.sh"
source "${working_dir}/_sourced/messages.sh"

# use -z to check the length of string receive as a params is zero. 
# {1+x} returns nothing is no params
if [[ -z ${1+x} ]]; then
  message_error "Filename is missing. Please specify the backup filename"
  exit 1
fi

# set default folder filename. eg: /backups/backup_2024_02_29T13_07_00.sql.gz
backup_filename="${BACKUP_DIR_PATH}/${1}"

if [[ ! -f "${backup_filename}"  ]]; then
  message_error "This backup file is not found."
  exit 1
fi

message_welcome "Restoring the '${POSTGRES_DB}' database from the ${backup_filename}..."

if [[ "${POSTGRES_USER}" == "postgres" ]]; then
  message_error "Restoring as 'postgres' user is not allowed. Assign 'POSTGRES_USER' env with another one and try again."
  exit 1
fi

export PGHOST="${POSTGRES_HOST}"
export PGPORT="${POSTGRES_PORT}"
export PGUSER="${POSTGRES_USER}"
export PGPASSWORD="${POSTGRES_PASSWORD}"
export PGDATABASE="${POSTGRES_DB}" 

message_info "Dropping the database..."

dropdb "${PGDATABASE}"

message_info "Creating new database..."

createdb --owner="${POSTGRES_USER}"

message_info "Applying the backup to new database..."

gunzip -c "${backup_filename}" | psql "${POSTGRES_DB}"

message_success "The '${POSTGRES_DB}' database has been restored successfully from the '${backup_filename}'"